### ISSUE TITLE
fixed residues?

### ISSUE THREAD

**Issue by ojdoha** [bigict/ProDESIGN-LE#1]
hi
can I fix some known amino acids in structure and predict other amino acids?

**Comment by deltadbu** [comment]
Yes, this is supported by ProDESIGN-LE. 

Actually, we fixed some key esidues when we re-designed GFP and Protein A and finally made the redesigned GFP light and the redesigned Protein A bind with its ligand. 

Best wishes,
Dongbo

**Comment by huangbinapple** [comment]
Hi [ojdoha](https://github.com/ojdoha), please see the main page for instruction.
